### ISSUE TITLE
Make this handle the empty string. 

### ISSUE THREAD

**Issue by Tombert** [Tombert/Vertigo.CsvParse#1]
https://github.com/Tombert/Vertigo.CsvParse/blob/f3d9fc6c7f868c61066ba3f645e60202d6d45bc5/Library.fs#L34

**Comment by Patricknew** [comment]
For the record, I found out this issue :D

**Comment by Tombert** [comment]
Fixed in the latest commit: https://github.com/Tombert/Vertigo.CsvParse/commit/6c342b5ff4dd5a40ca9cebf9457259393adbb73f
