### ISSUE TITLE
Environment.NewLine

### ISSUE THREAD

**Issue by pengo98** [Tombert/Vertigo.CsvParse#2]
https://github.com/Tombert/Vertigo.CsvParse/blob/f3d9fc6c7f868c61066ba3f645e60202d6d45bc5/Library.fs#L19

Could we use Enviornment.NewLine here instead of '\n' and '\r' so it's not platform specific ?

**Comment by Tombert** [comment]
This particular line isn't actually handling the newline, it's handling how we *parse* the escape characters. 
All this basically says is treat `"\" + "n"` as the singular token `\n` instead of the two-character string `"\n"`

**Comment by Tombert** [comment]
Just as a note, FParsec's `newline` combinator, which I use, should handle this: http://www.quanttec.com/fparsec/reference/charparsers.html#members.newline
